project:
  type: default
  output-dir: docs

format:
  revealjs:
    theme: [default, ../styles.scss]
    slide-number: true
    hash-type: number
    center: false
    transition: fade
    transition-speed: fast
    width: 1280
    height: 720
    margin: 0.1
    lang: bg
    fig-align: center
    code-overflow: wrap
    highlight-style: github
    footer: "Вземане на бизнес решения на базата на данни | НБУ"
    logo: ""
